kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: k8sc-vol-per-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: k8sc-vol-per-volume